---
title: "Analiza danych_HR"
author: "Aleksandra Łada, Marcin Skowronek, Maryia Vashkevich"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    highlight: kate
    toc: true
    toc_dephth: 3
    theme: "red"
    self_contained: true
    number_sections: true
    code_folding: show
    Fig_width: 8
    Fig_height: 5
    Fig_caption: true
---

```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE)
dane <- read.csv("HR.csv")
library(tidyverse)
```

# 1. Wprowadzenie

Celem raportu jest analiza firmowych danych HR za dany okres. Raport zawiera przegląd najważniejszych wskaźników, wizualizację danych oraz wyciągnięte wnioski. Zbiór danych zawiera `r nrows(dane)` wierszy oraz `r ncols(dane)` kolumny.

# Pytania badawcze

1. Czy nadgodziny i niskie zadowolenie ze środowiska zwiększają ryzyko odejścia pracownika?
2. Czy pracownicy z niższym miesięcznym wynagrodzeniem lub rzadkimi awansami odchodzą częściej?
3. Jaka jest charakterystyka (wiek, staż pracy) pracownika, który najczęściej decyduje się na odejście?
4. Które działy oraz stanowiska są najbardziej narażone na odejścia pracowników?

# Opis danych

Dane HR obejmują następujące kolumny:

1.	Age	-	Wiek
2.	Attrition	-	Odejście z firmy
3.	BusinessTravel	-	Podróże służbowe
4.	DailyRate	-	Dzienne wynagrodzenie
5.	Department	-	Dział
6.	DistanceFromHome	-	Odległość od domu
7.	Education	-	Wykształcenie
8.	EducationField	-	Kierunek wykształcenia
9.	EmployeeCount	-	Liczba pracowników
10.	EmployeeNumber	-	Numer pracownika
11.	EnvironmentSatisfaction	-	Satysfakcja ze środowiska pracy
12.	Gender	-	Płeć
13.	HourlyRate	-	Stawka godzinowa
14.	JobInvolvement	-	Zaangażowanie w pracę
15.	JobLevel	-	Poziom stanowiska
16.	JobRole	-	Rola w pracy
17.	JobSatisfaction	-	Satysfakcja z pracy
18.	MaritalStatus	-	Stan cywilny
19.	MonthlyIncome	-	Miesięczne wynagrodzenie
20.	MonthlyRate	-	Miesięczna stawka
21.	NumCompaniesWorked	-	Liczba firm, w których pracował(a)
22.	Over18	-	Powyżej 18 lat
23.	OverTime	-	Nadgodziny
24.	PercentSalaryHike	-	Procentowa podwyżka wynagrodzenia
25.	PerformanceRating	-	Ocena wydajności
26.	RelationshipSatisfaction	-	Satysfakcja z relacji w pracy
27.	StandardHours	-	Standardowe godziny pracy
28.	StockOptionLevel	-	Poziom opcji na akcje
29.	TotalWorkingYears	-	Łączny staż pracy
30.	TrainingTimesLastYear	-	Liczba szkoleń w ostatnim roku
31.	WorkLifeBalance	-	Równowaga między pracą a życiem prywatnym
32.	YearsAtCompany	-	Lata w firmie
33.	YearsInCurrentRole	-	Lata na obecnym stanowisku
34.	YearsSinceLastPromotion	-	Lata od ostatniego awansu
35.	YearsWithCurrManager	-	Lata współpracy z obecnym przełożonym

# 2. Porządkowanie i czyszczenie danych 

# 2.1 Braki danych

